### ISSUE TITLE
Configuration Provider

### ISSUE THREAD

**Issue by KodrAus** [emit-rs/emit#14]
It'd be great if there was some standard configuration provider that abstracted fetching collector configuration, so support for env vars/yaml/json/something in code could be used without impacting the collector.

Maybe something like:

``` rust
trait ReadConfig<'a> {
    //Load from the provider (file to serde_json::Value, serde_yaml::Value etc), or get env_vars with prefix
    fn load(&'a mut self);
    //Get a collection of config values for a section
    fn section(&'a self, name: &str) -> HashMap<&'a str, &'a ConfigValue>;
    //Get a single value
    fn value(&'a self, name: &str) -> &'a ConfigValue;
}
```

What do you think?

**Comment by nblumhardt** [comment]
Sounds like something that would be good to integrate with the design early on :+1: - I haven't given the specifics any thought, looks like you're further along that path than me. The 'static bound ticket looks like it needs attention for this, I'll try to make it my next target :-) !!!

**Comment by KodrAus** [comment]
Sounds good :) Yeh the lifetime of the config would have to be at least as long as the pipeline, since collectors would be using borrowed values, right? My thought was that you could then add a trait method to collectors like this:

```rust
fn from_config<'a>(config: &ReadConfig<'a>) -> Self;
```

**Comment by KodrAus** [comment]
I was thinking I might have to start coding something up for configuration, but this [config](http://codinghighway.com/rust-config/config/) crate looks pretty useful.

**Comment by nblumhardt** [comment]
Wow, yes, nice syntax. Would [TOML](https://crates.io/crates/toml) be the more widespread format in Rust apps though?

**Comment by KodrAus** [comment]
That's a good question... There's the [toml-rs](http://alexcrichton.com/toml-rs/toml/index.html) crate for parsing toml config, which cargo uses, so it'd have to be pretty stable. Then you could keep config formats more consistent.
