### ISSUE TITLE
Template Replacement

### ISSUE THREAD

**Issue by KodrAus** [emit-rs/emit#16]
For collectors that don't support templates like `Seq` does it'd be good if we could replace templates on the collector.

@nblumhardt raised the point about caching the work done to build up a replacement struct, which is a great idea, since templates would be pretty much always provided as static string literals, so they won't change for the lifetime of the program.

**Comment by KodrAus** [comment]
@nblumhardt How do you feel about using a `MessageTemplateRepl` in the `stdio` collector to print replaced messages to console instead of the template?

**Comment by nblumhardt** [comment]
Sounds like a good move :+1:

It'd also be nice to separate formatting from the output destination, e.g. so that the `stdio` sink could just as easily emit JSON. I'd like to whip up a formatter for the schema in https://github.com/nblumhardt/serilog-formatting-compact ... :-)

**Comment by KodrAus** [comment]
Ah interesting! That would highlight the benefit of treating events as structures until the last possible moment. It'd be neat to have some general purpose collector that just takes a formatter and a `Write` and dumps events into it. You could then use that for writing to a file/socket/whatever.

**Comment by KodrAus** [comment]
I think this is looking pretty good now, are you happy if we close this issue?
