### ISSUE TITLE
Compact property representation

### ISSUE THREAD

**Issue by nblumhardt** [emit-rs/emit#26]
Currently, we use `BTreeMap` to hold the properties associated with an event.

This makes lookup `O(log n)` when the number of properties is more than a few, but the additional space requirements and indirection in `BTreeMap` needs to be quantified. 

Using `[(&'a str, Value)]` will be the most compact, and since lookups are infrequent, might be a better choice. Laying out the values so that the first `n` are always the `n` elements in the message eliminates lookup in the most common scenario anyway.

**Comment by KodrAus** [comment]
All for using `[&'a str, Value)]` if we can get away with it. I wonder if there are other ways to take advantage of the way properties are used; for each call to `em*!` in usercode, we have a single bag of properties where the size and keys don't change, but the values do. I think it'd be worthwhile doing some benches of different representations along with `mem::size_of_val` to find a compact and performant candidate
