### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by KodrAus** [emit-rs/emit#29]
- [x] Status badge for README
- [x] CI for docs
- [x] Link to docs in README

A tracking issue for adding Travis CI to Emit. While I'm at it I was planning on adding some more benches to various bits of plumbing so performance changes can be tracked.

**Comment by nblumhardt** [comment]
- [ ] Status badge for README

Anything else left before we close this one?

**Comment by KodrAus** [comment]
What did you want to do about docs? The script we're using can automagically upload docs to the `gh-pages` branch of this repo

**Comment by nblumhardt** [comment]
`gh-pages` would be great :+1:

**Comment by KodrAus** [comment]
Now we just need to add a link to http://emit-rs.github.io/emit/emit/index.html in the README
