### ISSUE TITLE
Merging in rewrite

### ISSUE THREAD

**Issue by KodrAus** [emit-rs/emit#44]
I've been working on a rewrite of this project over here for the last few years: https://github.com/KodrAus/emit

I've published an alpha release on crates.io so I can start linking up documentation etc. It's still in need of a proper test suite, more examples, more documentation, but I think is ready to pull in here and start working on through a proper collaborative process.

My plan to get it all in is:

1. Archive the other repos here and note that they're built for an older version of the framework
2. PR the new source and its CI in here just over the top of the existing code
3. Archive my fork
4. Publish a new alpha release with all the repository links updated
5. Close any open issues that are no longer relevant

How does this sound to you @nblumhardt?

**Comment by nblumhardt** [comment]
Sounds awesome @KodrAus 👍 

Until I have a chance to contribute someday, I should probably step out of this organisation or at least drop the "owner" role - let me know if that works for you :-)

**Comment by KodrAus** [comment]
No problem :) Thanks for originally bootstrapping this! I've got the new source pulled in and few organization settings updated.
