### ISSUE TITLE
A plan for ETW support

### ISSUE THREAD

**Issue by nblumhardt** [emit-rs/emit#8]
Event id generation (hashed?), manifest generation (compiler plugin).

**Comment by KodrAus** [comment]
Is this separate from the [jenkins hash](https://github.com/emit-rs/emit/blob/master/src/formatters/json/mod.rs#L116) being generated when using using the `RenderedJsonFormatter`?

**Comment by nblumhardt** [comment]
Howdy, yes, ETW support requires some level of handling for manifests, which map event ids to what are effectively message templates describing how the payload of the event should be rendered. I think there are some options for integration that avoid them, but IIRC they're not optimal.
