### ISSUE TITLE
Find a contention-free way to push events into the pipeline

### ISSUE THREAD

**Issue by nblumhardt** [emit-rs/emit#9]
The current event pipeline uses `std::sync::mpsc`. The initial idea was that senders could enqueue events without blocking each other, to be received at the other end by the collector.

The major problem with this design, discovered late in the process, is that `Sender` is not `Sync`, with the expected usage calling for a per-sender `clone()` to give each an independent handle to the pipeline.

Since logging may occur on arbitrary threads it's awkward to do this. The implementation sidesteps the issue currently by sharing a single `Sender` under a `Mutex` (see _pipeline.rs_).

Fast logging in a concurrent web app/API requires a contention-free approach. Help/ideas/suggestions on this would be greatly appreciated!

**Comment by schets** [comment]
The crossbeam blocking MSQueue, or a BlockingQueue implemented on SeqQueue would be a good start and neither would require too much extra code.

The most optimal approach would probably be either a MPSC queue based on on the SegQueue (which I'll submit to crossbeam at some point) or a mix of a bounded+nonallocating spmc queue with some sort of overflow backup.

**Comment by nblumhardt** [comment]
Thanks for the pointer, `MSQueue` looks like a promising option!

`SegQueue` looks interesting. I think this ticket probably needs to be approached in two phases, removing the current high-contention implementation (e.g. by switching to `MSQueue`) and then optimising for other characteristics :+1:

**Comment by schets** [comment]
FWIW, on my laptop, in the mpsc scenario, a truly contended MsQueue is ~150ns/push+pop, the channel is ~120ns, SeqQueue is ~50ns, and the SeqMpScQueue is ~30ns. Now, the last two don't support blocking so that would add some overhead, and I would expect these all to have worse measurements on a multi-socket server.

150ns isn't too bad in the grand scheme of things, definitely better than a contended mutex.

**Comment by KodrAus** [comment]
I've used `MsQueue` elsewhere and it's quite nice to work with, I think it's a good option :+1:
